### ISSUE TITLE
Array  index  is  out of bound in Today class 

### ISSUE THREAD

**Issue by RaoKamran** [PIAIC-IOT/Quarter1_Batch3#1]
fn main() { let list = [22,33,44,55,66];
    print!("Complete Array : {:?} \n\n\n",list);
    
    print!("Fourth Index {} \n\n\n\n",list[4]);
    let temp = 8;
    print!("Fourth Index {} \n",list[8]); // COMPILER SHOW ERROR

}

**Comment by imran82ali** [comment]
Dear Rao,

We were discussion in class regarding how we will get compiler Error and how we will get Panic Error.  We did this deliberately.

Thanks,
